name: Deploy to Github Pages
permissions:
  contents: write

on:
  push:
    branches: [frontend]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: frontend

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Build
        run: |
          yarn install
          yarn build
          yarn export

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: out
          clean: true
          single-commit: true